# Generated by Django 3.0.14 on 2022-11-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.CharField(max_length=30)),
                ('order', models.IntegerField(null=True)),
                ('stop_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Line')),
                ('reportstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.User')),
            ],
        ),
    ]
